name = "SpatialAccessTrees"
uuid = "c0867ef0-7eb8-477c-bc68-2f3754ecb96a"
authors = ["Eric S. Tellez <donsadit@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimilaritySearch = "053f045d-5466-53fd-b400-a066f88fe02a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
